### ISSUE TITLE
Información sensible en Github

### ISSUE THREAD

**Issue by cr0hn** [cybercamp18isecurity/iSecurityWebService#1]
No es una buena práctica poner IP de producción

<img width="641" alt="isecuritywebservice_configuration_ini_example_at_develop_ _cybercamp18isecurity_isecuritywebservice" src="https://user-images.githubusercontent.com/4076390/49303255-8b736700-f4c9-11e8-8101-eae0bbd521a5.png">

**Comment by megavexus** [comment]
Arreglado. Era sólo el esqueleto, por eso no me preocupé, pero gracias.
